// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeEndpoint() Endpoint {
	config := NewConfig()
	endpoint := NewEndpoint(config)
	return endpoint
}
