// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/ZacharyGroff/GitHooks/config"
	"github.com/ZacharyGroff/GitHooks/endpoint"
	"github.com/ZacharyGroff/GitHooks/processors"
	"github.com/ZacharyGroff/GitHooks/validation"
)

// Injectors from wire.go:

func InitializeEndpoint() endpoint.Endpoint {
	configConfig := config.NewConfig()
	deployer := processors.NewDeployer(configConfig)
	pushProcessor := processors.NewPushProcessor(deployer, configConfig)
	validator := validation.NewValidator(configConfig)
	endpointEndpoint := endpoint.NewEndpoint(configConfig, pushProcessor, validator)
	return endpointEndpoint
}
